version: '3.8'

services:
  flask:
    build: .
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: app/my_flask.py
    command: ["flask", "run", "--host", "0.0.0.0"]
    volumes:
      - .:/flask