version: '3.8'

services:
  flask:
    build: .
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: app/my_flask.py
      # without the following variables flask wont restart on code changes
      FLASK_ENV: development
      FLASK_DEBUG: 1 
    volumes:
      - ./app:/flask/app   # This line binds the local 'app' directory to the '/flask/app' directory in the container -
      # it wont show up in docker desktop or docker volume ls presumably becausing it is bind volume?
    command: ["flask", "run", "--host", "0.0.0.0"]