version: "3"
services:
  app:
    build: ./flask
    links:
      - db
    ports:
      - "5000:5000"
    volumes:
      - ./flask:/flask # This line binds the local 'flask' directory to the '/flask' directory in the container

  db:
    image: mysql:5.7

    platform: linux/amd64 # Specify the platform here
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
